#!/usr/bin/env bun

// Build-time skill embedding.
// Reads all skills/<name>/SKILL.md files and generates lib/skills-data.ts
// with their contents as string constants.

import { readdirSync, existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const SKILLS_DIR = join(import.meta.dir, "../../skills");
const OUTPUT = join(import.meta.dir, "skills-data.ts");

const skills: Record<string, string> = {};

for (const dir of readdirSync(SKILLS_DIR).sort()) {
  const md = join(SKILLS_DIR, dir, "SKILL.md");
  if (existsSync(md)) {
    skills[dir] = readFileSync(md, "utf-8");
  }
}

const count = Object.keys(skills).length;
const code = `// AUTO-GENERATED by skills-gen.ts — do not edit
export const SKILLS: Record<string, string> = ${JSON.stringify(skills, null, 2)};
`;

writeFileSync(OUTPUT, code);
console.log(`Embedded ${count} skills into lib/skills-data.ts`);
